name: Group JSON API

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: npm install
            - run: npm run group-data
            - run: |
                  git config user.name hojlund123
                  git config user.email zere0.mail@gmail.com
                  git add .

                  git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Group JSON API"

                  git push origin main
